version: '3'
services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared-Vaultwarden
    restart: always
    network_mode: host
    command: tunnel --no-autoupdate run --token eyJhIjoiZjYzYWEyZjI2OTRjNGIyNjk2NTZkNGE1MDgzM2UzY2YiLCJ0IjoiZjgwMTc5NzctZjA0Yi00ZjUwLWJkNDAtMjczZjhhZDg4NmIwIiwicyI6Ik56RTFPVFUwTkRndE5XTmxaQzAwWWpBNUxUZ3daRGd0WkRVelpHSXpOV1UxWmpJNSJ9
